apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-app
  template:
    metadata:
      labels:
        app: proxy-app
    spec:
      containers:
      - name: proxy-app
        image: rutujamalpute/three-tier:nginx_image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
