apiVersion: v1
kind: Pod
metadata:
 name: myvolsecret
spec:
 containers:
 - name: c01
   image: centos
   command: ["/bin/bash","-c","while true;do echo rutuja; sleep 5; done"]
   volumeMounts:
   - name: testsecret
     mountPath: "/tmp/secrets"
 volumes:
 - name: testsecret
   secret:
     secretName: mysecret
